trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/payments-api/chart/**
      - scripts/helm/**
      - .azuredevops/templates/helm-chart-ci-template.yml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/payments-api/chart/**
      - scripts/helm/**
      - .azuredevops/templates/helm-chart-ci-template.yml

extends:
  template: ../templates/helm-chart-ci-template.yml
  parameters:
    chartName: payments-api
    chartPath: src/payments-api/chart
    kubernetesVersion: '1.35.0'
